SUPPORTED_LANGUAGES = ("en-us", "zh-cn")
DEFAULT_LANGUAGE = "en-us"


def localization(Language, index):
    """Return the localized text for index, falling back to English.

    An unknown or empty Language (e.g. when config.json is missing and the
    caller never assigned one) falls back to DEFAULT_LANGUAGE instead of
    raising UnboundLocalError.
    """
    if(Language not in SUPPORTED_LANGUAGES):
        Language = DEFAULT_LANGUAGE
    if(Language == "en-us"):
        Language_switcher = {
            "Set Countdown (seconds)...": "Set Countdown (seconds)...",
            "Set Countdown": "Set Countdown",
            "Enter total seconds (e.g. 300 = 5min):": "Enter total seconds (e.g. 300 = 5min):",
            "Load JSON...": "Load JSON...",
            "Select JSON file": "Select JSON file",
            "JSON files (*.json)": "JSON files (*.json)",
            "Set Karma Level (1-10)...": "Set Karma Level (1-10)...",
            "Set Karma Level": "Set Karma Level",
            "Enter Karma level (1-10):\n(6-10 auto-set maxKarma=10)": "Enter Karma level (1-10):\n(6-10 auto-set maxKarma=10)",
            "Zoom": "Zoom",
            "Zoom In (+0.2)": "Zoom In (+0.2)",
            "Zoom Out (-0.2)": "Zoom Out (-0.2)",
            "Reset Zoom (1.0)": "Reset Zoom (1.0)",
            "Settings": "Settings",
            "Set Language...": "Set Language...",
            "Set Language": "Set Language",
            "changes of Language made will be applied after this software restarting.": "changes of Language made will be applied after this software restarting.",
            "Set Show Hotkey...": "Set Show Hotkey...",
            "Set Show Hotkey": "Set Show Hotkey",
            "Enter new hotkey combination (e.g. 'ctrl+shift+f' or 'alt+x'):": "Enter new hotkey combination (e.g. 'ctrl+shift+f' or 'alt+x'):",
            "Need at least one non-modifier key": "Need at least one non-modifier key",
            "Hotkey": "Hotkey",
            "Show hotkey set to": "Show hotkey set to",
            "Invalid hotkey:": "Invalid hotkey:",
            "Please try again.": "Please try again.",
            "Set Quit Hotkey...": "Set Quit Hotkey...",
            "Set Quit Hotkey": "Set Quit Hotkey",
            "Enter new quit hotkey combination (e.g. 'ctrl+shift+q' or 'alt+q'):": "Enter new quit hotkey combination (e.g. 'ctrl+shift+q' or 'alt+q'):",
            "Quit hotkey set to": "Quit hotkey set to",
            "Invalid quit hotkey:": "Invalid quit hotkey:",
            "Sound:": "Sound:",
            "ON": "ON",
            "OFF": "OFF",
            "Toggle Always on Top": "Toggle Always on Top",
            "Always on Top": "Always on Top",
            "Set to": "Set to",
            "Toggle Show/Hide": "Toggle Show/Hide",
            "Quit": "Quit",
            "Rain Cycle Timer - Settings Editor": "Rain Cycle Timer - Settings Editor",
            "Wave & Vibration": "Wave & Vibration",
            "Intervals": "Intervals",
            "General": "General",
            "Save to config.json": "Save to config.json",
            "Export as JSON file...": "Export as JSON file...",
            "Export JSON": "Export JSON",
            "Saved": "Saved",
            "Configuration saved successfully.": "Configuration saved successfully.",
            "Exported": "Exported",
            "JSON exported to": "JSON exported to",
            "Failed to save:": "Failed to save:",
            "Save Failed": "Save Failed",
            "Failed to save configuration. Close anyway?": "Failed to save configuration. Close anyway?",
            "Failed to export:": "Failed to export:",
            "Wave Duration (s):": "Wave Duration (s):",
            "Total duration of wave in seconds": "Total duration of wave in seconds",
            "Shrink Amount:": "Shrink Amount:",
            "Shrink amount (0.05 = scale to 0.95)": "Shrink amount (0.05 = scale to 0.95)",
            "Shrink Duration Ratio:": "Shrink Duration Ratio:",
            "Shrink duration ratio of total wave time": "Shrink duration ratio of total wave time",
            "Recover Duration Ratio:": "Recover Duration Ratio:",
            "Recover duration ratio of total wave time": "Recover duration ratio of total wave time",
            "Max Radius Ratio:": "Max Radius Ratio:",
            "Max wave radius ratio (clamped to 0.75 to avoid edge clipping)": "Max wave radius ratio (clamped to 0.75 to avoid edge clipping)",
            "Vibration total:": "Vibration total:",
            "Wave starts at:": "Wave starts at:",
            "Pips": "Pips",
            "Time(s)": "Time(s)",
            "Karma": "Karma",
            "Reinf.": "Reinf.",
            "MaxKarma": "MaxKarma",
            "Add Row": "Add Row",
            "Remove Selected": "Remove Selected",
            "Data Error": "Data Error",
            "Row": "Row",
            "has invalid data:": "has invalid data:",
            "Language:": "Language:",
            "Show Hotkey:": "Show Hotkey:",
            "Quit Hotkey:": "Quit Hotkey:",
            "Zoom Scale:": "Zoom Scale:",
            "Sound Enabled:": "Sound Enabled:",
            "Ticktock (s):": "Ticktock (s):",
            "Interval between tick and tock sounds (seconds)": "Interval between tick and tock sounds (seconds)",
            "Error": "Error"
        }
    if(Language == "zh-cn"):
        Language_switcher = {
            "Set Countdown (seconds)...": "设置倒计时 (秒)...",
            "Set Countdown": "设置倒计时",
            "Enter total seconds (e.g. 300 = 5min):": "输入总秒数 (例如 300 = 5 分钟):",
            "Load JSON...": "加载 JSON 配置文件...",
            "Select JSON file": "选择 JSON 文件",
            "JSON files (*.json)": "JSON 文件 (*.json)",
            "Set Karma Level (1-10)...": "调整业力符号等级 (1~10)...",
            "Set Karma Level": "设置业力符号等级",
            "Enter Karma level (1-10):\n(6-10 auto-set maxKarma=10)": "输入业力符号等级 (1-10):\n(若输入 6-10 则自动设置最大业力为10)",
            "Zoom": "调整窗口大小",
            "Zoom In (+0.2)": "窗口放大 (+0.2)",
            "Zoom Out (-0.2)": "窗口缩小 (-0.2)",
            "Reset Zoom (1.0)": "重置窗口大小 (1.0)",
            "Settings": "设置",
            "Set Language...": "设置语言...",
            "Set Language": "设置语言",
            "changes of Language made will be applied after this software restarting.": "语言的更改将在本软件重启后应用",
            "Set Show Hotkey...": "自定义显示热键...",
            "Set Show Hotkey": "自定义显示热键",
            "Enter new hotkey combination (e.g. 'ctrl+shift+f' or 'alt+x'):": "输入新的热键组合 (例如 ctrl+shift+f 或 alt+x):",
            "Need at least one non-modifier key": "需要至少一个非修饰键 (修饰键：Ctrl、Shift、Alt和win)",
            "Hotkey": "热键",
            "Show hotkey set to": "显示热键已修改为",
            "Invalid hotkey:": "无效热键：",
            "Please try again.": "请再试一次",
            "Set Quit Hotkey...": "自定义退出热键...",
            "Set Quit Hotkey": "自定义退出热键",
            "Enter new quit hotkey combination (e.g. 'ctrl+shift+q' or 'alt+q'):": "输入新的退出热键组合 (例如 ctrl+shift+q 或 alt+q):",
            "Quit hotkey set to": "退出热键已修改为",
            "Invalid quit hotkey:": "无效退出热键:",
            "Sound:": "全局声音：",
            "ON": "开",
            "OFF": "关",
            "Toggle Always on Top": "切换窗口置顶",
            "Always on Top": "窗口置顶",
            "Set to": "修改为",
            "Toggle Show/Hide": "切换显示/隐藏",
            "Quit": "退出",
            "Rain Cycle Timer - Settings Editor": "雨循环计时器 - 设置编辑器",
            "Wave & Vibration": "波浪与振动",
            "Intervals": "区间列表",
            "General": "通用",
            "Save to config.json": "保存到 config.json",
            "Export as JSON file...": "导出为 JSON 文件...",
            "Export JSON": "导出 JSON",
            "Saved": "已保存",
            "Configuration saved successfully.": "配置已成功保存",
            "Exported": "导出成功",
            "JSON exported to": "JSON 文件已导出至",
            "Failed to save:": "未能保存：",
            "Save Failed": "保存失败",
            "Failed to save configuration. Close anyway?": "无法保存配置【不会翻】",
            "Failed to export:": "导出失败：",
            "Wave Duration (s):": "波浪持续时间 (秒)：",
            "Total duration of wave in seconds": "波浪的总持续时间 (以秒为单位)",
            "Shrink Amount:": "收缩量:",
            "Shrink amount (0.05 = scale to 0.95)": "业力符号收缩量 (0.05 = 缩放至 0.95)",
            "Shrink Duration Ratio:": "收缩持续时间比:",
            "Shrink duration ratio of total wave time": "波浪持续时的业力符号收缩持续时间比",
            "Recover Duration Ratio:": "舒张持续时间比:",
            "Recover duration ratio of total wave time": "波浪持续时的业力符号舒张持续时间比",
            "Max Radius Ratio:": "最大半径比:",
            "Max wave radius ratio (clamped to 0.75 to avoid edge clipping)": "波浪的最大半径比 (0.75 以下可避免因窗口大小的剪切)",
            "Vibration total:": "振动总值：",
            "Wave starts at:": "波浪开始时间：",
            "Pips": "圆点总数",
            "Time(s)": "波浪持续时间 (秒)",
            "Karma": "业力等级",
            "Reinf.": "是否显示强化花环",
            "MaxKarma": "最大业力等级",
            "Add Row": "添加行",
            "Remove Selected": "移除所选项",
            "Data Error": "数据错误",
            "Row": "第",
            "has invalid data:": "行存在无效数据：",
            "Language:": "语言：",
            "Show Hotkey:": "显示热键:",
            "Quit Hotkey:": "退出热键:",
            "Zoom Scale:": "窗口大小:",
            "Sound Enabled:": "声音开关:",
            "Ticktock (s):": "嘀嗒声周期 (秒):",
            "Interval between tick and tock sounds (seconds)": "嘀声和嗒声之间的间隔 (秒)",
            "Error": "错误"
        }
    return Language_switcher.get(index, "Index_Error")